### ISSUE TITLE
 CuDNN error: CUDNN_STATUS_INTERNAL_ERROR

### ISSUE THREAD

**Issue by J-zin** [speedinghzl/Pytorch-Deeplab#20]
hi, i use it to train for my own data set, but it run error, can u give me some suggestion? (my segmentation class img is gray image).

/opt/conda/conda-bld/pytorch_1532581333611/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:99: void cunn_SpatialClassNLLCriterion_updateOutput_kernel(T *, T *, T *, long *, T *, int, int, int, int, int, long) [with T = float, AccumT = float]: block: [3,0,0], thread: [190,0,0] Assertion `t >= 0 && t < n_classes` failed.
/opt/conda/conda-bld/pytorch_1532581333611/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:99: void cunn_SpatialClassNLLCriterion_updateOutput_kernel(T *, T *, T *, long *, T *, int, int, int, int, int, long) [with T = float, AccumT = float]: block: [3,0,0], thread: [191,0,0] Assertion `t >= 0 && t < n_classes` failed.
Traceback (most recent call last):
  File "train.py", line 234, in <module>
    main()
  File "train.py", line 215, in main
    loss.backward()
  File "/home/zhangjunyi/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/tensor.py", line 93, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/zhangjunyi/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: CuDNN error: CUDNN_STATUS_INTERNAL_ERROR

**Comment by J-zin** [comment]
i got it, the gray num must be lower than the class nums!!!

**Comment by Raven1327** [comment]
> i got it, the gray num must be lower than the class nums!!!

I got the same problem. Could you please teach me how to fix it?

**Comment by speedinghzl** [comment]
@Raven1327 Do you run this repo on PASCAL VOC dataset or another dataset? You can simply modify the NUM_CLASSES in [this line](https://github.com/speedinghzl/Pytorch-Deeplab/blob/master/train.py#L33) for your dataset.

**Comment by Raven1327** [comment]
@speedinghzl Thanks for your help. It can run now. I made some mistakes. T-T

**Comment by Helens1997** [comment]
@speedinghzl  I use VOC dataset， NUM_CLASSED=21, i also get the same problem
